# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: LSST DESC DC2 Analysis
author: LSST DESC
copyright: "2024"
logo: logo.png
exclude_patterns: [".github"]

execute:
  execute_notebooks: off

html:
  use_issues_button: true
  baseurl: https://lsstdesc.github.io/DC2-analysis

launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url            : "https://jupyter.nersc.gov"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)

repository:
  url: https://github.com/LSSTDESC/DC2-analysis
  branch: master
